version: '2'

services:
  db:
    image: postgres:9.6.5-alpine
    restart: always
    volumes:
      - ${POSTGRES_PATH}:/var/lib/mysql
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nextcloud

  nextcloud:
    image: nextcloud:12.0.3-apache
#    build: ./nextcloud
    restart: always
    depends_on:
        - db
        - code
    ports:
      - 8181:80
    links:
      - db
    volumes:
      - ${NEXTCLOUD_PATH}/config:/var/www/html/config
      - ${NEXTCLOUD_PATH}/data:/var/www/html/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin

  code:
    build: ./CODE
    restart: always
    ports:
        - 8182:9980
    environment:
       - domain=${CODE_URL}
#       - domain=collabora.${NEXTCLOUD_URL}
       - username=test
       - password=test
       - servername=localhost:8182
    cap_add:
        - MKNOD
    # https://help.nextcloud.com/t/how-o-install-collobora-without-domain-and-ssl/5995/2

  draw_io:
    build: ./draw.io
    restart: always
    ports:
      - 8183:80
    #environment:
      #- NODE_ENV="true"
